spring.application.name=qjrun

spring.datasource.url=jdbc:postgresql://localhost:5432/qjrun
spring.datasource.username=postgres
spring.datasource.password=qjrun26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# JWT
# ==========================

jwt.secret=VXFKUnVuMjAyNk15U3VwZXJTZWNyZXRLZXlGb3JKV1RUb2tlbjEyMzQ1Njc4OTBBQkNERUY=
jwt.expiration=86400000